env: "local"
http_server:
    address: "localhost:3001"
    timeout: 5s
    idle_timeout: 60s
storage:
    db_port: 5432
    db_host: "localhost"
    db_password: "vuigxuishgbgiufs"
    db_name: "checkers"
    db_user: "postgres"
